name: Deployment

on:
  release:
    types:
      - published
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout sources
      uses: actions/checkout@v4

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3

    - name: Prepare for publish
      run: |
        ./gradlew publish \
          -PreleaseVersion="${{ github.event.release.tag_name }}" \
          -Psigning.keyId="${{ secrets.SIGNING_KEY_ID }}" \
          -Psigning.password="${{ secrets.SIGNING_PASSWORD }}" \
          -Psigning.secretKeyRingFile="${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}"

    - name: Release in Maven Central
      run: |
        ./gradlew jreleaserRelease \
          -PreleaseVersion="${{ github.event.release.tag_name }}" \
          -PmavenCentralUsername="${{ secrets.MAVEN_CENTRAL_USERNAME }}" \
          -PmavenCentralPasswordToken="${{ secrets.MAVEN_CENTRAL_PASSWORD_TOKEN }}" \
          -PgithubToken="${{ secrets.GITHUB_TOKEN }}"


  update:
    runs-on: ubuntu-latest
    steps:
      - name: Update release description

        run: |
          existingDescription=$(gh release view ${{ github.event.release.tag_name }} --repo ${{ github.repository }} --json body -q '.body')
          
          newDescription='[Maven Repository](https://central.sonatype.com/artifact/io.github.damirdenis-tudor/kabbitmq/${{ github.event.release.tag_name }})'

          updatedDescription="${newDescription} \\n ${existingDescription}"

          gh release edit ${{ github.event.release.tag_name }} --repo ${{ github.repository }} --notes "$updatedDescription"
    env:
      GH_TOKEN: ${{ github.token }}